### ISSUE TITLE
Selecting items other than the first two taps needed

### ISSUE THREAD

**Issue by Justinzobel** [budgie-desktop/budgie-run-dialog#1]
Hard to summarize.. When hitting down after typing a search query it doesn't move. You have to hit it again to start it moving. Just a tiny UX improvement.

**Comment by fossfreedom** [comment]
issue as described here: https://github.com/budgie-desktop/budgie-desktop/issues/942

**Comment by ikeydoherty** [comment]
Also this repo is unused. :)

**Comment by Justinzobel** [comment]
@ikeydoherty is it possible to disable issues on it so others aren't posting here as well?

**Comment by ikeydoherty** [comment]
Shouldn't really need to .. all issue links point to the budgie-desktop one. Always have.

**Comment by ikeydoherty** [comment]
Actually I'll delete the unused repos - makes more sense
